[MIG] SQS connector migration odoo 17.0
awisky/odoo-sqs pull request #2
Opened 2024-04-28 14:19 UTC by rejamen

2024-04-28 14:44 UTC, awisky reviewed
nice

2024-04-28 14:46 UTC, awisky requested changes
Nice Icon @r

2024-04-28 14:46 UTC, awisky commented on sqs/static/description/sqs_menu_icon.png
Niceeeee Icon 🥇

2024-04-29 15:31 UTC, rejamen commented
@awisky I deleted pycache files.

2024-04-29 22:34 UTC, awisky approved these changes

2024-04-29 22:34 UTC, merged